import React from "react";
import Head from "next/head";
import styles from "../../../styles/LayoutWeather.module.css";
const LayoutWeather = ({ children }) => {
  return (
    <>
      <Head>
        <title>Thời tiết Việt Nam</title>
        <link rel="icon" href="/sun-regular.svg" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header>ABCS</header>
      <main>{children}</main>
    </>
  );
};

export default LayoutWeather;
